### ISSUE TITLE
HTML Validator is Failing

### ISSUE THREAD

**Issue by Ahhorse1** [cse110-fa22-group6/cse110-fa22-group6#100]
https://github.com/cse110-fa22-group6/cse110-fa22-group6/actions/runs/3570970448/jobs/6002429151
![image](https://user-images.githubusercontent.com/46540636/204491414-b79a833d-04c7-421c-becd-9656cb6e05e3.png)
HTML Validator is failing for our logo images

**Comment by tyler-le** [comment]
What branch should I branch off of to make the changes?
