### ISSUE TITLE
Main Branch issues after latest merge 

### ISSUE THREAD

**Issue by awesomesup** [cse110-fa22-group6/cse110-fa22-group6#148]
### Firstly, some of the actions are failing 
<br>

<img width="1178" alt="Screenshot 2022-12-08 at 1 12 54 AM" src="https://user-images.githubusercontent.com/77423340/206406872-bb0e1327-2aa6-4a53-b1c5-da05cdab921e.png">

<br> 

## Secondly, add window pop up is messed up. 

<br>

<img width="1670" alt="Screenshot 2022-12-08 at 1 15 05 AM" src="https://user-images.githubusercontent.com/77423340/206407244-99107598-fa69-465b-883c-f0f5f43433c7.png">

**Comment by tyler-le** [comment]
Frontend Issue fixed #149
