### ISSUE TITLE
Brainstorming Activity

### ISSUE THREAD

**Issue by tyler-le** [cse110-fa22-group6/cse110-fa22-group6#3]
**Describe the solution you'd like**

To demonstrate that you understand this potential SE stage, teams should schedule at least 1 (but as many as they require) brainstorming meetings.  The brainstorming effort should be at minimum 2 hours in length and be documented in terms of attendance, time, tool/location.  The class suggested tool for Brainstorming in a remote condition is [Miro](https://miro.com/) which provides both whiteboarding and remote collaboration features to conduct this process.  You are not required to use Miro though and may use another tool if it works better for your team.  Regardless of how you perform your brainstorming effort, to define the problem you must save the following artifacts in your project repository.

**/admin/meetings/mmddyy-brainstorm.md** (there may be multiple of these)  - these are the general meeting notes of the brainstorming summarized including attendance, etc.  Note this may be more exhaustive and procedural as opposed to what will be found in the planning document

**/specs/brainstorm/** will continue the distilled documents and diagrams you produced of the ideas you want to capture from your meetings.  If you used Miro or another tool export the contents as an image, PDF, or markdown file to capture your appropriate assets.

We don't want to tell you specifically what to discuss, but you should be narrowing down the problem you're solving and what features a system would need to address it. There are many ways you could do this: clarifying definitions and requirements, thinking about users and their expectations, deciding on your app's theme or mood, etc. It might also be helpful to "survey your competition." We're looking for evidence that you've sufficiently pondered your problem before diving into visual and technical design.

**Additional context**
Need to set up a meeting time.

**Comment by awesomesup** [comment]
- Each sections seperate brainstorm Miro images are uploaded and merged
- Meeting minutes from all Brainstorm meetings, except wednesday 101922, has been uploaded and merged.
- New issue has been created for JC to upload minutes from Wednesday'brainstorm meeting.

This issue is not ready to be closed yet
