### ISSUE TITLE
Conflict Between Prettier and Super-Linter

### ISSUE THREAD

**Issue by tyler-le** [cse110-fa22-group6/cse110-fa22-group6#44]
Currently, there is a conflict between Prettier and Super-Linter that causes Super-Linter to always fail.

Prettier will always add double quotes to strings in JavaScript files which then fails the lint (which requires single quotes). 

**TODO** We need to find a way to disable this check on the linter, or not to Prettify quotes, or get rid of one.

https://github.com/github/super-linter/blob/main/docs/disabling-linters.md

**Comment by Ahhorse1** [comment]
I'm assuming this is for markdown files?

**Comment by tyler-le** [comment]
@Ahhorse1 @mhm1117 After messing with it for a bit, I think we should remove Prettier because the two style checkers (Our linter and Prettier) have **several** conflicting rules.

**Comment by Ahhorse1** [comment]
Did we discuss in class/labs at any point whether it's better to use single/double quotes?

**Comment by tyler-le** [comment]
I'm not entirely sure. Super-Linter is also kind of annoying because it does not want semicolons at the end of lines. Maybe we should change the linter instead lol. It's also really strict in the fact that you cannot configure the linters' rules

**Comment by Ahhorse1** [comment]
Let's look into the linters that the TA reccomended

**Comment by tyler-le** [comment]
Super Linter just takes a bunch of linters for different languages and combines them. The TA recommended ESLint but that is what Super Linter uses for JS

 https://github.com/github/super-linter#supported-linters

**Comment by Ahhorse1** [comment]
Do we know if the conflicts are between ESLint or standard lint

**Comment by tyler-le** [comment]
Oh, that might be it. Should I just delete Super Linter and use the recommended linters from the TA?

**Comment by tyler-le** [comment]
Yeah that's what I thought. I read that Standard uses ESLint as the backend but Standard is unable to be changed

**Comment by Ahhorse1** [comment]
![image](https://user-images.githubusercontent.com/46540636/201746728-c67d5079-8791-4e15-814d-e575b4460383.png)

**Comment by Ahhorse1** [comment]
https://prettier.io/docs/en/integrating-with-linters.html
I'm looking into this right now

**Comment by tyler-le** [comment]
https://github.com/prettier/eslint-config-prettier

**Comment by tyler-le** [comment]
oh lol we found the same thing

**Comment by Ahhorse1** [comment]
I'm thinking we get rid of super linter, and just implement ESLint and CSSLint and that way we can install the eslint-config-prettier

**Comment by tyler-le** [comment]
Ok sounds goood

**Comment by mhm1117** [comment]
Anything I can help on with the new linter set-up? We won't need to change prettier now right? Just the configuration for eslint?

**Comment by mhm1117** [comment]
Will do

**Comment by mhm1117** [comment]
It couldn't run cause the source directory (assets/scripts/etc. doesn't exist on the main or our pipeline branches so I made a test js file in the directory to test on. Then I'll see how the linter runs otherwise.

**Comment by mhm1117** [comment]
There were some syntax errors with eslint.yml that I fixed but now i'm getting this error.
![image](https://user-images.githubusercontent.com/83431136/201761858-9fedbc1f-66b7-4d01-8da0-e39f673f56d5.png)

And I'm also getting an error for .eslintrc.yml. I was trying to look up the right structure for it but i'm pretty confused.
![image](https://user-images.githubusercontent.com/83431136/201762023-2203e649-1924-4c7a-af0d-6fa4246cf9f0.png)

Anyone have any ideas for these?
