### ISSUE TITLE
brainstorm notes/image/link upload for education/work group 

### ISSUE THREAD

**Issue by awesomesup** [cse110-fa22-group6/cse110-fa22-group6#5]
### Description: 
Convert meeting notes to markdown from google docs and add it to /admin/meetings/mmddyy-brainstorm.md and add the image and link to image to /specs/brainstorm/

Meeting date: 10/20/2022

**Comment by tyler-le** [comment]
Miro image uploaded on branch tle-brainstorm-educational.

**Comment by awesomesup** [comment]
Added brainstorm md for our group for thursdays meeting. This issue is can be closed when tyler merges his branch with main
