### ISSUE TITLE
warnings with css linter build

### ISSUE THREAD

**Issue by mhm1117** [cse110-fa22-group6/cse110-fa22-group6#50]
![image](https://user-images.githubusercontent.com/83431136/201797749-a6e2bd9a-dfd3-4329-a1a7-184d101d21b1.png)

1. Not sure if the license field matters since it's just a warning or what to put to resolve that.
2. Conflicting package managers with ESLint (package-lock.json) file. Also just a warning but its not recommended and might run into more issues of different linters being inconsistent with each other. Not sure if that's issue with the linter, though I was looking us CSSLint and they both seem to implement the same stylelint so not sure if that would help. Not sure what the solution is for this.

**Comment by tyler-le** [comment]
hm i don't think it should be a big deal but honestly I'm not sure of the effect that the warnings can have

**Comment by mhm1117** [comment]
should i do pull request to pipeline anyways and we can just see how it behaves with frontend stuff at least once we merge all that?
based off pipeline checkpoint instructions it seems fine if we still have some of the pipeline stuff not fully functional in case it does cause issues

**Comment by tyler-le** [comment]
up to JC but i think it's fine if we merge now and fix later if it causes any issues
