### ISSUE TITLE
Wing Icon not centered on Edit / Add

### ISSUE THREAD

**Issue by tyler-le** [cse110-fa22-group6/cse110-fa22-group6#56]
The Wing logo is not centered vertically on the edit and add pages. Feel free to make changes directly on `tle-frontend-integration`

@tamarasagakova it uses the code you wrote for "Delete Application" but I couldn't get it centered on "Edit" and "Add" for some reason. Maybe you can take a look? 

<img width="800" alt="Screenshot 2022-11-16 at 2 26 48 AM" src="https://user-images.githubusercontent.com/15850172/202156176-4c3a37f0-4e55-4217-aeff-92b6b1697d24.png">
<img width="800" alt="Screenshot 2022-11-16 at 2 26 41 AM" src="https://user-images.githubusercontent.com/15850172/202156185-3ef79f3d-8a83-418d-9575-8a14c0acb07a.png">

**Comment by tamarasagakova** [comment]
Solved
