### ISSUE TITLE
Job Card is not fully responsive

### ISSUE THREAD

**Issue by tyler-le** [cse110-fa22-group6/cse110-fa22-group6#70]
The progress bar for the job card begins to break when we shrink the width. In order to support several screen sizes, we need to shrink the font/size of the position, company, and location while increasing the size of the progress bar.

<img width="710" alt="Screenshot 2022-11-18 at 12 11 26 AM" src="https://user-images.githubusercontent.com/15850172/202653100-a2411cd1-a8e0-461b-98fd-ec126f4e9c07.png">

**Comment by tamarasagakova** [comment]
Solved
