### ISSUE TITLE
"Update" Deletes Information If Left Blank

### ISSUE THREAD

**Issue by tyler-le** [cse110-fa22-group6/cse110-fa22-group6#73]
So if I have a completely filled out job like this:
<img width="1301" alt="Screenshot 2022-11-19 at 10 25 14 AM" src="https://user-images.githubusercontent.com/15850172/202865972-a4843b82-6a4a-4adc-acd1-cd8687da81cb.png">
But I just want to update **only** the company, I would have to press 'Edit Icon' > Type the new company > Edit:
<img width="480" alt="Screenshot 2022-11-19 at 10 26 22 AM" src="https://user-images.githubusercontent.com/15850172/202866025-5ee83be4-9557-49ac-96c0-3ad27a251361.png">
But since we left the other fields blank, it deletes those fields and replaces it with the empty string:
<img width="1300" alt="Screenshot 2022-11-19 at 10 27 55 AM" src="https://user-images.githubusercontent.com/15850172/202866077-d3042c9a-0771-42e9-a0b9-457d7e3328ec.png">

Is this intended? I think if the user didn't want to edit a specific part, they can just leave it blank and when we press 'Edit', that part won't be edited. It will edit only the field(s) that weren't left blank.

**Comment by JongminKim292** [comment]
Solved (in backend branch)
