### ISSUE TITLE
Small Bug in ESLint Causing it to Fail

### ISSUE THREAD

**Issue by tyler-le** [cse110-fa22-group6/cse110-fa22-group6#98]
The linter fails due to the following reason in the testing branch. 

<img width="1013" alt="Screenshot 2022-11-28 at 10 47 22 PM" src="https://user-images.githubusercontent.com/15850172/204458441-89f27d9a-16e6-4bc0-aecd-61c112b263b1.png">

**Comment by awesomesup** [comment]
Maybe try this?

https://github.com/parcel-bundler/parcel/issues/2287
